[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/rais.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/hisobot.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/rais"
  to = "/rais.html"
  status = 200

[[redirects]]
  from = "/hisobot"
  to = "/hisobot.html"
  status = 200
